### ISSUE TITLE
[Mod suggestion] Chisel Refabricated

### ISSUE THREAD

**Issue by Fr3qz** [Kasax007/Modpack-Development#11]
First off great modpack, I have had a great time with it.
I didn't find any information on the topic of mod suggestions and therefore I wanted to ask if mod suggestions are desired.

If they are, I wanted to make the suggestion of adding Chisel Refabricated (https://www.curseforge.com/minecraft/mc-mods/fabric-chisel) with it's dependency Continuity (https://www.curseforge.com/minecraft/mc-mods/continuity) to improve upon building block variety.

I appreciate all your work.

**Comment by Kasax007** [comment]
Hey, thanks for the nice words and I am glad to hear you enjoy the modpack! 
And yes mod suggestions are desired :) 
I will take a look at your mods and see if I can add them with the next update. 
I had issues with Chisel in the past but hopefully that is fixed now.

**Comment by Kasax007** [comment]
Your mods have been added in the V6 update! :)
