### ISSUE TITLE
[Mod suggestion] Botania (Fabric)

### ISSUE THREAD

**Issue by Fr3qz** [Kasax007/Modpack-Development#13]
I additionally wanted to suggest the Fabric version of Botania (https://www.curseforge.com/minecraft/mc-mods/botania-fabric), because I think it will add more depth to magic in the pack with it's progression system.

I already added the mod to the pack locally and it seems to work just fine, but I could not test it with shaders yet.

**Comment by Kasax007** [comment]
Will be added in the v8 update

**Comment by Kasax007** [comment]
finally added with v8 update
