### ISSUE TITLE
ZIP does not include mods

### ISSUE THREAD

**Issue by Oxydark** [Kasax007/Modpack-Development#14]
when i want to install this pack outtside of curseforge (e.g. MultiMC) and download your zip there are no mods...

**Comment by Kasax007** [comment]
There is a weblink inside the zip with all the mods in there or the link in the README. Other than that I do not support these websites and only develop for Curseforge. Hence if they removed that file from the zip before uploading it to their website I cant change anything about it. You can always download the right zip from Curseforge.
