### ISSUE TITLE
Registry remapping failed

### ISSUE THREAD

**Issue by Oxydark** [Kasax007/Modpack-Development#15]
played a bit on a server withou any problems. after i logged out and tried to reconnect to the server i get the "registry remapping failed" error.

Singleplayer works perfectly fine. But joining my server results always in this failure

[latest.log](https://github.com/Kasax007/Modpack-Development/files/7920980/latest.log)
.

**Comment by Kasax007** [comment]
I am not sure but this could be a multi mc issue. I would suggest to try and launch it on the curseforge launcher. Other then that I cant spot a issue right now. Let me know if the Curseforge launcher fixes the issue.

**Comment by Kasax007** [comment]
Ich könnte auch versuchen dem Server beizutreten. Falls ich das selbe Problem bekomme kann ich vielleicht in meinem log mehr Infos finden. Mein username ist "iwaL"

**Comment by Oxydark** [comment]
Ah, deutsch schreiben machts natürlich einfacher.

Ich hatte ursprünglich auf Curseforge gespielt und hatte am Anfang kleine Probleme. Habe den Client und den Server mit der (an dem Tag) aktuellen Version installiert und kam dann auch problemlos drauf.
Eine Freundin hatte direkt beim ersten Versuch direkt eine Liste mit Problemen, die (ingame) aus dem Bildschirm raus ging. Das war aber auch mit den remapping. Sie hat dann alles neu installiert und die Fehlerliste ging auf ein remapping runter.
Dann habe ich ihr meine Mod-Dateien gegeben (weil es ja bei mir funktioniert hat) und dann ging es bei ihr auch.

Dann nach ein paar Stunden, wie oben beschrieben einmal ins Hauptmenü rein und dann war der eine remapping fehler da.
Dann versucht mit neu Installation aber da dann Cursforge auch nur noch Probleme gemacht hat zu MultiMC gegangen aber selben fehler bekommen.


Habe es eben nochmal Probiert (mit einer neuen Cursforge Installation) und es funktionierte wieder.
Ich bekam nur eine meldung das ich die Config dateien Synchronisieren musste.

Ich werde es mal ein bisschen Probieren ob es wieder auftaucht und wenn ja, kann ich gerne nochmal die logs hier rein geben, falls du es wünscht.

**Comment by Kasax007** [comment]
Ja gerne logs helfen immer weiter :) Ich hoffe aber natürlich dass das Problem aus bleibt. Einen mod habe ich im Hinterkopf der das Problem mit dem nächsten Update vielleicht beseitigen kann. 
Soweit aber erstmal viel Spaß beim weiterspielen.

**Comment by Oxydark** [comment]
So, nachdem gestern alles wunderbar funktionierte habe ich heute wiedermal den
"Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:game_event contains IDs unknown to the receiver!
 - minecraft:click"
 fehler beim joinen bekommen. 
 kann es was mit den server-seitigen mods zu tun haben?
Eine aus der Gruppe kam scheinbar heute drauf.

Habe dich jetzt mal in die Whitelist eingetragen. Kannst es ja auch mal probieren ob/wie/wann die probleme auftreten.

Anbei wieder das log:
[latest 2022-01-26.log](https://github.com/Kasax007/Modpack-Development/files/7943162/latest.2022-01-26.log)

**Comment by Kasax007** [comment]
Hey, danke für die ganzen logs. Hoffe ich kann den Fehler finden. Bin bis nächste Woche Donnerstag jedoch sehr beschäftigt mit Uni und kommt vermutlich vorher nicht dazu nach einem fix zu schauen. 
Hoffentlich kommt ihr auch so vorerst zumindest wieder auf den server. 
Ich kann die zwei logs komischer weise nicht herunterladen und github gibt mir nur einen Fehler aus. 
Du kannst sie entweder nochmal probieren zu senden oder auch über Discord gerne an mich schicken: Kasax#4613

**Comment by babel5405** [comment]
I have been getting his issue as well, with multiple clients involved. I personally use GD Launcher, while some of the others use MultiMC.

Here are a few logs that could be relevant:

This is the first log from the day, it was split and archived for some reason.
https://pastebin.ubuntu.com/p/5Y2CgW22Dn/

Here is the second, which is the first place I note the issue occurring:
https://pastebin.ubuntu.com/p/C74nczcY2d/

I'm sure I have other logs, but I would have to sort through them to find any archived latest logs which are involved. I will note my server install isn't exactly standard, as noted in this closed issue: https://github.com/Kasax007/Modpack-Development/issues/16

I also have a few crash logs, which may or may not be related:
https://pastebin.ubuntu.com/p/pSvCmrNhHT/
https://pastebin.ubuntu.com/p/gPB444Ck6F/
https://pastebin.ubuntu.com/p/pDkxBN7Bts/

**Comment by Oxydark** [comment]
yes after multiple test we figured out that server restart does the trick. (But this should not be the solution)

But i have to say that after updating everything to v7 we did not encounter the issue again (yet).
(server was up till yesterday and a friend played about 8h and could get right back in and i could join after 5h without problems)

**Comment by Ariaszzzhc** [comment]
@Kasax007 Does v7 Server still ok? I've met this issue on my v8 server.
My server runs to this issue per several minutes, that's intolerable.
These Modpack is quite awesome. So if v7 server didnt has this issue, that's very good

**Comment by Gwydion5** [comment]
**To Reproduce**
1: Play some time on a Server (maybe go into the Nether it happened often after going into it)
2: Leave the Server 
3: Join Server 
4. There you are :
![grafik](https://user-images.githubusercontent.com/90518494/154106089-ee58e79a-fe22-4373-8587-5312623135fe.png)


**Expected behavior**
Joining the server 

**Screenshots + Crash log**
[13.02 12:44:17] [Server] [Netty Epoll Server IO #18/ERROR]: Could not serialize INSTANCE (class com.blamejared.crafttweaker.api.command.argument.CTRecipeTypeArgument) - will not be sent to client!
[13.02 12:44:17] [Server] [Netty Epoll Server IO #18/ERROR]: Could not serialize INSTANCE (class com.blamejared.crafttweaker.api.command.argument.CTItemArgument) - will not be sent to client!

After removing crafttweaker the 2. Log entry didn't appear anymore.

**Version of the modpack**
Minecraft: 1.18.1 Modpack:1.0.14 Server Pack: V8

**Additional context**
To fix the problem and be able to connekt to the server and for a few hours until it appers again it helped to reinstall Fabric API.

**Comment by Zeroethan** [comment]
We're also getting the same issue; server is fine for an hour or so after a restart and then no one is able to connect due to 'Registry remapping failed'

Most recent server log:
https://pastebin.com/WD4E4Vm7

**Comment by enosich** [comment]
checking in, neither server nor client show us any log that could be beneficial to actually determining the issue.

this bug report should not be closed until the issue is both found and fixed.

**Comment by Oxydark** [comment]
> > @Oxydark Does v7 Server still ok? I've met this issue on my v8 server. My server runs to this issue per several minutes, that's intolerable. These Modpack is quite awesome. So if v7 server didnt has this issue, that's very good
> 
> I am really sorry about this issue. Could you send the console log, when this issue occurs? I might have an idea what causes the problem, but I need to verify my guess. Also this shouldn't kick you from the server and just prohibit you from joining again right?

still no issues on V7. haven't played much the last few day but still..

**Comment by Kasax007** [comment]
If this is actually related to the fabric API maybe messing with some mod it might be fixed with the next update, in which I am updating the Fabric API to a newer version. Other than that I am sadly out of ideas what might cause this since the console log doesn't really make it clear what mod causes this and a brute force fix with testing until the issue comes up would just take way too long. I will try to release the update as soon as possible. For now, I can just suggest everyone who is getting this issue in the v8 server to use the v7 version since there that issue shouldn't be there (hopefully). 
Really sorry about this.

**Comment by Kasax007** [comment]
Also in the v8 try to remove crafttweaker entirely and its config files.

**Comment by Kasax007** [comment]
It might be related to this issue: https://github.com/CraftTweaker/CraftTweaker/issues/944
Also, anyone who gets this issue, after you cant reconnect please type /ct log in to the console and upload the log here.

**Comment by Kasax007** [comment]
I found a fix. Go to your client's config files and delete the Polymer Folder. That solved all issues for me.

**Comment by enosich** [comment]
> I found a fix. Go to your client's config files and delete the Polymer Folder. That solved all issues for me.

this doesn't fix the issue, unfortunately.

**Comment by Kasax007** [comment]
Okay, that's weird. For me it did, after that, I didn't get the error anymore. I deleted the folder from my client and server.

**Comment by Kasax007** [comment]
Released the v9 version of the mod pack which should finally remove this issue again. I was able to play for hours without getting the issue now.

**Comment by Zeroethan** [comment]
We're still having the issue with v9. I was unable to run the /ct log command while connected to a server and it doesn't seem to work inside the server console either


![unknown](https://user-images.githubusercontent.com/46986968/154743433-ea539674-037d-49cb-a089-56f0ae81e6db.png)

![Capture](https://user-images.githubusercontent.com/46986968/154743511-15d68258-24a2-4fb1-81bd-144333b50103.PNG)
.

**Comment by jaredlll08** [comment]
While the main issue isn't CraftTweaker related, please can you make an issue for not being able to open the log through the command on the Crafttweaker issue tracker

**Comment by Kasax007** [comment]
> ~While the main issue isn't CraftTweaker related, please can you make an issue for not being able to open the log through the command on the Crafttweaker issue tracker~
> 
> Actually just fixed it, so no issue needed

Quick mod developer at work 👌
