### ISSUE TITLE
Problems downloading zip from Mega

### ISSUE THREAD

**Issue by babel5405** [Kasax007/Modpack-Development#16]
I have tried downloading the mods from the (Mega) link provided in the curseforge zip and have failed numerous times on different browsers, different computers, and different networks (had someone else test it). I don't know that there is much you can do for it but did want to report that there appears to an issue of some kind with the download.

The download (zip) will start, report temporary errors, then fail to continue.

**Comment by Kasax007** [comment]
You can also just download the modpack on curseforge then click on browse local files and drag over the mods then. You will have to remove one mod from the server tho I think Gizmos. With it in there it wont start.

**Comment by babel5405** [comment]
I'll give that a go in a little while, I almost tried it but wasn't certain if there were any server-specific mods or configs and couldn't be bothered with comparing every single mod and config file for what may be a known or temporary issue. I appreciate the response and if it works, I'll leave an additional reply and close the ticket.

**Comment by Kasax007** [comment]
Sounds good. I guess you were trying to download the V6 mods?

**Comment by babel5405** [comment]
Had to go back and check what was linked on CurseForge, but yeah. the V6 mods linked in the zip from the **Server Pack [FABRIC] 1.18.1 v6**

I just got freed up so I'm going to test grabbing the client mods and pulling the Gizmos mod right now.

**Comment by babel5405** [comment]
Copying the mods from the client (Minus Gizmo) worked just fine. Thanks.

**Comment by Kasax007** [comment]
Have fun playing!
