### ISSUE TITLE
can't see all quests in achievements menu

### ISSUE THREAD

**Issue by CommonFungus** [Kasax007/Modpack-Development#17]
when I open the achievements menu for the quests, I can only see a certain number of tabs before they go off the screen.

either fix this or make a proper quests menu, thanks!

**Comment by Kasax007** [comment]
I am aware of this issue. I tried adding a quest book but it wouldn't work with the modpack. I had to release the new version without it. I am trying to add it with the next update tho.

**Comment by CommonFungus** [comment]
> I am aware of this issue. I tried adding a quest book but it wouldn't work with the modpack. I had to release the new version without it. I am trying to add it with the next update tho.

cool, for now I just had to make my GUI smaller. looking forward to the update!

**Comment by Kasax007** [comment]
In newest update Quests were released to no more need for advancements. Still something I want to fix tho!
