### ISSUE TITLE
Strongholds Not Spawning

### ISSUE THREAD

**Issue by RockerBuck** [Kasax007/Modpack-Development#19]
I've been trying to check out everything in the pack in creative mode, and I can't get to the End because I can't find any strongholds. I use eyes of ender like you should, and they point me to a location, but there's nothing there. No strongholds, end portals - anything.  Usually just solid blocks.
I'm still using the version with the spawn glitch (spawning in the same place every time) - I'll see if I can find the latest version and try again. If it works then - disregard this message, and you have have an AWESOME pack!! I'm really enjoying it so far!

**Comment by RockerBuck** [comment]
I just tried it in the latest version, and it does the same thing. 
I haven't fully explored the modpack, but could you tell me to how to find a stronghold in the Overworld? I'd love to check out the End and see what it has to offer......

**Comment by Kasax007** [comment]
Oh, that is a big issue and obviously shouldn't be like this. Did you just update your version and tried to find the stronghold in the same world? Since that won't work. 
I created a new world on the newest version and the stronghold always spawns for me.

**Comment by RockerBuck** [comment]
No, I updated the version and created a whole new world.
The stronghold wasn't there. I'll try creating a new world and try again.
Perhaps it's an issue being in creative??  I even tried making my own end portal LOL. That didn't work either...hehe

**Comment by RockerBuck** [comment]
Ok, I tried a new world, and this time it worked....yay!!
Thanks for your patience.....this is awesome!! I've never seen the End looking so beautiful...and interesting!!
Thanks so much for your hard work!!

**Comment by Kasax007** [comment]
Good to hear somehow this issue has fixed itself. Also yeah the end generation is really awesome. Same with the Nether if you haven't seen that yet either :) 
Have fun playing!

**Comment by RockerBuck** [comment]
I'm going to try a few new worlds just to make it wasn't fluke LOL.
The first new world also had horrible frame rates with shaders, even though I allocated 8 GB to be sure I had enough.
The second one, with the the stronghold, had better frame rates. Quite interesting. Either way, thanks again!!
