### ISSUE TITLE
INMIS Backpack swaps with armor instead of opening inventory

### ISSUE THREAD

**Issue by Incognito357** [Kasax007/Modpack-Development#23]
**Describe the bug**
When a chest plate is equipped, right clicking with a backpack in-hand swaps the backpack with the chest plate, instead of opening the backpack's inventory. Right clicking on the chest plate swaps back to the backpack.

**To Reproduce**
1. Equip chest plate
2. Select backpack in hot bar
3. Right click on backpack
4. Backpack moves to the armor slot, and the chest plate is put in your hand

**Expected behavior**
Backpack's inventory opens

**Version of the modpack**
MC: 1.18.1
Mod: v9

**Additional context**
I can't find what mod is enabling the right-click functionality to put armor into the armor slots. It seems like for some reason the backpack takes on the qualities of the equipped armor, since the tooltip for the backpack also displays the stats for the armor when hovering over the backpack. The hotkey works, but since it prioritizes the trinket slot, this bug prevents me from opening a secondary backpack that isn't in the trinket slot, unless I swap the backpacks or remove the chest plate first.

**Comment by Kasax007** [comment]
Yeah, I also noticed that it switches with the chest plate when testing. The backpack is intended to be put in the trinket slot and then to be opened with "b". That should work as you said. I don't know why it switches with the chest plate but I will see if I can find a reason for it and maybe disable it in the configs.
