### ISSUE TITLE
Game Lag

### ISSUE THREAD

**Issue by IsabellaSky** [Kasax007/Modpack-Development#24]
**Describe the bug**
After I play a while (min 1h+) or disconnect and reconnect from the server a few times (my boyfriend and i only play on the server and he doesn't get this issue nor we get any lag issues) my fps constantly dies down to 0-6 fps every 10-20 seconds and my screen freezes at the same time. I can only fix this by restarting the game. (I have around 6.3GB allocated) 

**To Reproduce**
1. play game for a while or disconnect and reconnect to server a few times
2. watch as fps dies down between 0-6 repeatedly while freezing the game

**Expected behavior**
To not get this issue

**Screenshots + Crash log**
If applicable, add screenshots and crash logs to help explain your problem.
I don't but i can try record it if needed

**Version of the modpack**
Game and modpack Version
Dreamcraft [FABRIC 1.18.1], v: 1.0.14

**Additional context**
my boyfriend thought it could relate to fps dynamics or fps reducer as to why i get this issue but so far it doesn't seem to be the cause. We also checked my CPU and all in task manager and they didnt seem to be the cause either

**Comment by Kasax007** [comment]
Hey, thanks for reporting this issue. First of all I would suggest you update to the v10 version of the mod pack, which I just released yesterday. With every update, I fix issues and update mods to the newest version. Since your issue is already 2 versions ago if this comes from a single mod, there is a high chance it is fixed now. Regardless I will do some testing in the v10 version to see if this issue is still here and if I can find out what causes it. Also, the v10 version is my favorite update yet :) So it's worth it to update!

**Comment by IsabellaSky** [comment]
Hey! Thanks for replying!! I will see with my boyfriend about updating to the newest. Also I think I may have found out as to what could be a potential culprit on my end. Yesterday I checked my storage and I only had about 8GB of free space left so what could have been happening is that it was freezing up after a bit (or disconnecting and reconnecting to the server a few times) due to lack of space left on the laptop

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by IsabellaSky** [comment]
Small update, we went on the newest version and I freed up a lot of storage and I still got the issue so I think it’s more so a bug then

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Kasax007** [comment]
Yeah, I have gotten multiple reports of it happening now. Make sure you have allocated enough ram to the game as well. Weirdly enough I never encountered this issue.

**Comment by IsabellaSky** [comment]
Actually I tried that earlier but I lowered the ram amount by 1GB and it pretty much doubled my fps. We didn’t play for too long so I haven’t gotten round to test to see if the issue still occurs however

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
