### ISSUE TITLE
Spectrum and spawners

### ISSUE THREAD

**Issue by linaraincalzando** [Kasax007/Modpack-Development#26]
Spawners when picked up change mod ownership from Minecraft to Spectrum and then when placed back down change from the original mob IE Blaze to Pig, This on the latest update using a silk touch pickaxe. 
![2022-03-11_12 10 24](https://user-images.githubusercontent.com/99147940/157925687-abb01aba-3d47-4deb-9e6a-efe1bad7c6dc.png)
![2022-03-11_12 11 14](https://user-images.githubusercontent.com/99147940/157925698-31b98a17-190c-4a27-b4ff-530313be9d60.png)
![2022-03-11_12 11 46](https://user-images.githubusercontent.com/99147940/157925705-d743ad52-0863-4ba7-aedf-2dafef95ca57.png)
![2022-03-11_12 11 58](https://user-images.githubusercontent.com/99147940/157925719-f9f0312e-5934-4ac4-9df0-eeead30ae167.png)
![2022-03-11_12 13 17](https://user-images.githubusercontent.com/99147940/157925924-876d632b-78fb-4e99-b7b8-0c634d802c54.png)

**Comment by Kasax007** [comment]
Hey, thanks for reporting this issue. It's definitely not supposed to be that way. Hopefully, I can fix it for the next update. Also nice gear you got there ;)

**Comment by linaraincalzando** [comment]
Thanks for looking into it! Tell me if you would like any additional information. Also thanks for the gear compliment :) I have put what is probably a stupid amount of time into this pack, it has been tons of fun!

**Comment by linaraincalzando** [comment]
Unfortunately it is single player and I ironically don't do a lot of building, I mostly explore. I have made it out over 400k blocks from spawn and omg I love being able to go into the dungeons and clearing them. Mapping is starting to get cranky with me. XD I do though I have a library I am building from all of the gear I am unenchanting and my villager trading post has over 30 villagers.
![Map](https://user-images.githubusercontent.com/99147940/158248861-6bf3df95-dff2-4a11-9e9b-754dc056d9d8.PNG)
![2022-03-14_14 35 00](https://user-images.githubusercontent.com/99147940/158248934-6b2ae640-a99c-4240-92a5-a5b62233f2b6.png)
![2022-03-14_14 35 42](https://user-images.githubusercontent.com/99147940/158248989-5386612d-18a6-4ccd-87ec-0ae510f56af5.png)

**Comment by Kasax007** [comment]
Holy waypoints haha that's insane.

**Comment by Kasax007** [comment]
Fixed with the upcoming release.
