### ISSUE TITLE
REI Crashes

### ISSUE THREAD

**Issue by Thanoid1** [Kasax007/Modpack-Development#27]
I was playing the modpack for sometime and then I was looking at a recipe for a fan from Kibe and then it crashed. I joined back and was looking at some other recipe's and I crashed as well.

This is the crash log for it.
[crash-2022-03-20_19.27.23-client.txt](https://github.com/Kasax007/Modpack-Development/files/8312398/crash-2022-03-20_19.27.23-client.txt)

**Comment by Thanoid1** [comment]
The latest version on curseforge.

**Comment by Kasax007** [comment]
Alright, I will have a look into it. Thanks for reporting.
