### ISSUE TITLE
Spectrum polished calcite is impossible to get

### ISSUE THREAD

**Issue by sharpskull2** [Kasax007/Modpack-Development#28]
**Describe the bug**
Consistency plus's smooth calcite recipe (smelting calcite in a furnace) overwrites the polished calcite recipe (smelting calcite in a furnace) from spectrum. This means that you can not start the mod or progress through it since it requires polished calcite.

**To Reproduce**
Smelt calcite in the furnace
**Screenshots + Crash log**
![image](https://user-images.githubusercontent.com/31316990/159264733-7e2e4ab7-b8b0-425c-a6eb-32b4de638f46.png)
![image](https://user-images.githubusercontent.com/31316990/159264880-82947dc0-01b4-480b-b182-4a3585fcc0bf.png)

**Version of the modpack**
1.18.1-1.0.17.fixed

**Comment by Kasax007** [comment]
Added with the update soon to be released.
