### ISSUE TITLE
Building Wands

### ISSUE THREAD

**Issue by sharpskull2** [Kasax007/Modpack-Development#29]
**Describe the bug**
The building wands recipe is the same as the javelin recipe from Medieval Weapons, when you try to craft a building wand you get a javelin instead

**Screenshots + Crash log**
![image](https://user-images.githubusercontent.com/31316990/159754816-a5e5d550-15ba-4b32-ba11-e8b4d8dca5d4.png)
![image](https://user-images.githubusercontent.com/31316990/159754855-816cfe90-b699-4e87-b122-8f438319af07.png)
the javelin recipe is shapeless and thus works in any orientations, thus overwriting the building wand recipe

**Version of the modpack**
1.18.1-1.0.17.fixed

**Comment by Kasax007** [comment]
For cases like this, a mod called "polymorph" should be in the pack but apparently, for this version, it isn't present anymore. Will be fixed next update.

**Comment by Kasax007** [comment]
Fixed with the upcoming release.
