### ISSUE TITLE
Polymorph does not work?

### ISSUE THREAD

**Issue by kever** [Kasax007/Modpack-Development#30]
Hi,

icon and funktion missing to me in your pack, so you cant choose the right reciepes, like eggs.
https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric

**Comment by Kasax007** [comment]
The mod should be in the pack for said reasons. If it somehow isn't in there anymore, it will be added back next update.

**Comment by Kasax007** [comment]
Fixed with the upcoming release.
