### ISSUE TITLE
Obtaining more than 1 Dragon egg

### ISSUE THREAD

**Issue by VitaHD** [Kasax007/Modpack-Development#36]
trying to obtain more than one dragon egg is seeming to be impossible. Ive tried the vanilla way of respawning the dragon and its not dropping anything besides EXP. There doesnt seem to be any other way of obtaining the dragon egg. There may be a way of getting that that i just dont know of. If you can can get back to me about this that would be greatly appreciated. Thank you!

**Comment by Kasax007** [comment]
I mean in vanilla you are not supposed to obtain more than one egg. Did I overlook a reason why one would need more than one egg? Also, you might wanna look into deep mob learning maybe you can get dragon eggs from there.

**Comment by VitaHD** [comment]
Well with the generator mod you can have a dragon generator which uses eggs to run them. And then with the seed mod you can also make a dragon egg seed. There could totally be a way with deep mob learning that I might not know about but yeah. Anyways thanks for responding!
