### ISSUE TITLE
Item Drops

### ISSUE THREAD

**Issue by CutzuDev** [Kasax007/Modpack-Development#43]
When i try to select an item in my inventory it drops the item

**Comment by Kasax007** [comment]
Please follow the bug report template. What version are you on of the mod pack, what operating system are you on, how can I reproduce this issue, etc. 

With just this description I have **no way** of fixing the bug since it doesn't happen for every player.

**Comment by CutzuDev** [comment]
**Describe the bug**
When i clicked on an item in my inventory it dropped it instead of selecting it

**To Reproduce**
I couldn't reproduce it

**Expected behavior**
To select the item

**Screenshots + Crash log**
None

**Version of the modpack**
Dreamcraft 1.19-1.0.21

**Additional context**
I disconnected and reconnected to my server and it fixed itself

**Comment by Kasax007** [comment]
Alright good to hear that the issue fixed itself. If it occurs again feel free to reopen this issue and maybe capture a video of the problem. 
For now have fun playing :)
