### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by hdmiport** [Kasax007/Modpack-Development#5]
I played around with the mod pack a little and would like to make some suggestions.
Litematica is kind of redundant and ultimately isn't going to be used by a vast majority of people who play on this mod pack. 
Also, Just Enough Items (JEI) introduces an incredible amount of lag when opening the inventory. I'm on a 3900xt/3080 build and I drop to mid 20s when my inventory is open.

**Comment by Kasax007** [comment]
Thanks a lot for the suggestions! It helps me improve the modpack. I will look into your suggestions and decide on them. 
Have fun playing :D 
(Do you really need all of the frames in the inventory? I mean you can turn the mod off for yourself in the REI settings :) )
