### ISSUE TITLE
nearly 0 vanilla animals in my world !

### ISSUE THREAD

**Issue by GGHoriZon** [Kasax007/Modpack-Development#6]
I started a survival world with my friend but I haven't found vanilla animals like horse, llamas yet. Moreover, I tried the command : /kill @e[type=horse] ( or other animals ), and it killed only 2 or 3 sheeps and 0 horses (it means there isn't any animal to kill so there aren't any animal on my world) . Even if that's set intentionnal, how can I edit the spawn rate of some vanilla animals? Thanks :) !

PS: I play on curseforge, in v3 realease (1.18.1). And I allowed about 9Gb of RAM.

**Comment by Kasax007** [comment]
Hey, this could be an issue with the world generation mod called Terralith. So I am afraid I can't do anything about it. But there are many cool new mounts for you to use as well from the mod mystic mounts. Maybe you can find one of those you like :D 
Have fun playing!
