### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by JetPorkins** [Kasax007/Modpack-Development#7]
I've tried this on both Mac and PC. The game crashes on launch in both. Is there anything I can do to get this modpack running?

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 12/28/21, 1:02 PM
Description: Unexpected error

java.lang.LinkageError: loader constraint violation: when resolving method 'void ca.weblite.objc.NSObject.<init>(com.sun.jna.Pointer)' the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @49c6c24f of the current class, net/minecraft/class_6417, and the class loader 'app' for the method's defining class, ca/weblite/objc/NSObject, have different Class objects for the type com/sun/jna/Pointer used in the signature (net.minecraft.class_6417 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @49c6c24f, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @67304a40; ca.weblite.objc.NSObject is in unnamed module of loader 'app')
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
	at net.minecraft.client.util.MacWindowUtil.getCocoaWindow(MacWindowUtil:21)
	at net.minecraft.client.util.MacWindowUtil.toggleFullscreen(MacWindowUtil:15)
	at net.minecraft.client.util.Window.updateWindowRegion(Window:349)
	at net.minecraft.client.util.Window.updateFullscreen(Window:387)
	at net.minecraft.client.util.Window.swapBuffers(Window:313)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1142)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_6417.method_37463(class_6417.java:21)
	at net.minecraft.class_6417.method_37461(class_6417.java:15)
	at net.minecraft.class_1041.method_4479(class_1041.java:349)
	at net.minecraft.class_1041.method_4485(class_1041.java:387)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Fabric Mods, loadmyresources.hiddenpack, KubeJS Resource Pack [assets]
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2409)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Mac OS X (x86_64) version 11.2
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1584976064 bytes (1511 MiB) / 2847932416 bytes (2716 MiB) up to 6777995264 bytes (6464 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 4.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel UHD Graphics 630 (Mobile)
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: Revision ID: 0x0005, Adapter Firmware Version: 7.55
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18432.00
	Virtual memory used (MB): 11701.97
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1619.75
	JVM Flags: 3 total; -Xss1M -Xmx6464m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 2.2.0
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancementplaques: Advancement Plaques 1.4.3
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.4.5
		ae2: Applied Energistics 2 10.0.0-alpha.7
		ae2wtlib: AE2WTLib 10.0.0-alpha.7
		agape_space: Space Dimensions 0.4.3
		alloy_forgery: Alloy Forgery 2.0.7+1.18
		amecsapi: Amecs API 1.3.3+mc1.18-pre1
		amplified_nether: Amplified Nether for Fabric 1.0.1
		animal_feeding_trough: Animal Feeding Trough 1.0.2+1.18
		appleskin: AppleSkin mc1.18-2.2.0
		aqupdcaracal: Caracal mob 1.18-1.3.4
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.1
		arcanus: Arcanus 1.24
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 3.2.51
		authme: Auth Me 2.1.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autosmeltenchant: AutosmeltEnchant 1.1.0
		axolotlitemfix: Axolotl Item Fix 1.1.3
		backslot: BackSlot 1.2.3
		backslotaddon: BackSlot Addon 1.0.7
		balm-fabric: Balm 2.3.0+0
		bannerpp: Banner++ 2.0.4+mc.1.18-rc4
		basicaiots: Basic AIOTs 1.3.2+1.18-pre1
		bclib: BCLib 1.0.3
		beenfo: Beenfo 1.18-fabric0.43.1-1.3.3
		betterf3: BetterF3 1.2.2
		betternether: Better Nether 6.0.3
		betterthirdperson: Better Third Person 1.5.4
		bewitchment: Bewitchment 1.18-2
		bitsandchisels: BitsAndChisels 2.6.1
		blast: BLAST 1.8.2
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		bno: Basic Nether Ores 1.18-7.0.0-Fabric
		boatcontainer: BoatContainer 1.0.4
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.3-1.18
		bountiful: Bountiful 2.0.1
		bowinfinityfix: Bow Infinity Fix rv11
		breakprogress: Break Progress 1.0.1
		buildinggadgets: st'ructure tools 1.0.6
		builtinservers: Builtin Servers 1.0.1-BETA+1.18
		camsbackpacks: Cammie's Wearable Backpacks 2.6
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		capes: Capes 1.2.2+1.18
		capybara: Capybara 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cardinal-components-item: Cardinal Components API (items) 4.0.0
		cardinal-components-level: Cardinal Components API (world saves) 4.0.0
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carrier: Carrier 1.9.0
		chalk: Chalk 1.1.1
		chas: Craftable Horse Armour & Saddle 1.18-1.8-Fabric
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chunky: Chunky 1.2.153
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 8.0.1
		coat: Coat 1.0.0-beta.15
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_draylar_omega-config: omega-config 1.0.8-1.17
		com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.0.0-1.18
		complete_bone_meal: Complete Bone Meal 1.3.0
		computercraft: CC:Restitched 1.99.1
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		conjuring: Conjuring 1.0.17+1.18
		connected-doors: Connected Doors 1.1+1.18
		consistency_plus: Consistency Plus 0.4.2+1.17
		controlling: Controlling For Fabric 9.0.4
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		cosmetica: Cosmetica 0.3.2
		couplings: Couplings 1.7.1+1.18
		craftingcraft: CraftingCraft 11.0.0
		craftingpad: Crafting Pad 1.0.7
		craftingtweaks: Crafting Tweaks 13.0.0
		craftpresence: CraftPresence 1.8.8
		crookedcrooks: Crooked Crooks 2.0.1+1.18.1
		croparia: Croparia 0.0.5
		croptopia: Croptopia 1.7.3
		croptosis: Croptosis 1.3.0
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cspirit: Christmas Spirit 1.1.3-1.18
		customportalapi: Custom Portal Api 0.0.1-beta47-1.18
		customwindowtitle: Custom Window Title 1.1.1
		danceofgrowth: Twerk / Crop Dusting Mod 1.0
		dark-enchanting: Dark Enchanting 0.6.1+1.18
		dashloader: DashLoader 3.0-rc11-1.18
		deathlog: DeathLog 0.2.4+1.18
		deepslatecutting: Deepslate Cutting 1.3.0
		defaultsettings: DefaultSettings 3.1.0
		detailab: Detail Armor Bar 2.6.1+1.18-fabric
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.1
		dev_quantumfusion_hyphen: hyphen 0.1
		diggusmaximus: Diggus Maximus 1.5.2-1.18
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dml-refabricated: Deep Mob Learning: Refabricated 0.5.0-beta2
		dml-refabricated-base: DML: Refabricated - Base 0.5.0-beta2
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.5.0-beta2
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.5.0-beta2
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.5.0-beta2
		dmlsimulacrum: Deep Mob Learning: Simulacrum 0.5.0-beta2
		dragonloot: DragonLoot 1.0.9
		drippyloadingscreen: Drippy Loading Screen 1.4.2
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.49b-fabric
		dynamicfps: Dynamic FPS 2.0.6
		dynmap: Dynmap 3.3-beta-2
		eatinganimationid: Eating Animation 1.2
		emerald_tools: Emerald Tools 1.3.31
		entitybanners: Entity Banners 1.0.2-BETA+1.18
		entityculling: EntityCulling-Fabric 1.3.3
		equipmentcompare: Equipment Compare 1.2.9
		exdel: Explorer's Delight 1.0.0-beta.3+1.18
		expandedstorage: Expanded Storage 7.3.3
		extragenerators: Extra Generators 1.1.1-BETA+1.18
		ezpas: Ezpas 2.0.0
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a14
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9514
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9514
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9514
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9514
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d9514
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9514
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9514
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a14
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9514
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5514
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabric-tree-chopper: Fabric Tree Chopper 0.8.0
		fabricloader: Fabric Loader 0.12.12
		fallingleaves: Falling Leaves 1.8.0+1.18
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		farsight: Farsight Mod 1.18-1.5
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		flesh2leather: Flesh2Leather 1.0.2
		forgeconfigapiport: Forge Config API Port 3.1.0
		fpsreducer: FPS Reducer 1.25-mc1.18
		gbfabrictools: GBfabrictools 1.3.4+1.18
		geckolib3: Geckolib 3.0.23
		geodes: More Geodes 1.2.0
		glassential: Glassential 1.3.0
		go-fish: Go Fish 1.4.1-1.18.1
		gobber2: Gobber2 2.5.53
		goblintraders: Goblin Traders 1.4.1
		goldenhoppers: Golden Hoppers 1.1.0
		golemsgalore: Golems Galore 1.1.0-1.18
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.1
		grindenchantments: Grind Enchantments 1.5.0+1.18
		guild: Guild 0.3.6
		hologram-api: Hologram API 0.2.1+1.18-pre5
		horseinfo: Horse Info 0.4.0-1.18
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		iceberg: Iceberg 1.0.27
		illuminations: Illuminations 1.10.2
		impaled: Impaled 1.0.2
		impersonate: Impersonate 2.4.0
		incantationem: Incantationem 1.1.2+1.18-pre1
		indium: Indium 1.0.2-alpha1+mc1.18
		infinitemusic: Infinite Music 1.3.0
		inventoryhud: Inventory HUD + 3.4.2
		inventorysorter: Inventory Sorter 1.8.1-1.18
		io_airlift_aircompressor: aircompressor 0.21
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.3
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kambrik: Kambrik 3.0.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.4-BETA+1.18
		kirin: Kirin UI 1.10.0-beta.2
		kjsextras: KubeJS Extras 1.5.0
		konkrete: Konkrete 1.3.2
		krypton: Krypton 0.1.6
		ktdatataglib: KtDataTagLib 1.6.4-1
		kubejs: KubeJS 1801.4.0-build.245
		kyrptconfig: Kyrpt Config 1.2.5-1.18
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.1.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		lifts: Lifts 1.4-BETA+1.18
		lightoverlay: Light Overlay 6.0.4
		litematica: Litematica 0.0.0-dev.20211203.013300
		lithium: Lithium 0.7.6
		loadmyresources: Load My Resources 1.0.1
		lovely_snails: Lovely Snails 1.0.3+1.18
		lumiwool: Luminous Wool 1.2.2
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		magna: Magna 1.7.0-1.18-pre1
		malilib: MaLiLib 0.10.0-dev.26
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-data: Maybe data 1.0.1-1.17
		maybe-more-data: Maybe More Data 1.0.0-1.18
		mcdict: MCDict 2.1.0+1.17.1
		medievalweapons: Medieval Weapons 1.1.7
		megane: megane 6.1.1
		megane-applied-energistics-2: megane-applied-energistics-2 6.1.1+10.0.0-alpha.1
		megane-base: megane-base 6.1.1
		megane-fabric-transfer: megane-fabric-transfer 6.1.1+1.5.4-b4f4f6cda9
		megane-kibe: megane-kibe 6.1.1+1.9.4-BETA-1.18
		megane-modern-industrialization: megane-modern-industrialization 6.1.1+1.0.0-alpha.02
		megane-reborn-core: megane-reborn-core 6.1.1+5.1.0-beta.2
		megane-runtime: megane-runtime 6.1.1
		megane-team-reborn-energy: megane-team-reborn-energy 6.1.1+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 6.1.1+5.1.0-beta.2
		megane-vanilla: megane-vanilla 6.1.1+1.18
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		minecraftcapes: MinecraftCapes Mod 12.0.0
		mining_dims: Mining Dimensions 1.2.36
		mm: Manningham Mills 2.3
		mob_catcher: Mob Catcher 1.1.18
		modern_industrialization: Modern Industrialization 1.0.0
		modmenu: Mod Menu 3.0.0
		more-axolotls: More Axolotls 1.0.2
		morerespawnanchors: More Respawn Anchors 1.0.3
		morevillagers-fabric: MoreVillagersFabric 3.0.0-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousetweaks: Mouse Tweaks 2.16
		mousewheelie: Mouse Wheelie 1.8.0+mc1.18-pre5
		mtmechs: Magitek Mechs 1.0.10
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		myron: Myron 1.6.2+1.18.1
		mythic-mounts: Mythic Mounts 4.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.6
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		notenoughanimations: NotEnoughAnimations 1.4.0
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18
		npcvariety: NPC Variety 2.2.1
		offlineskins: OfflineSkins 1.18.1-v1-fabric
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.18-1
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-compress: commons-compress 1.19
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		org_tukaani_xz: xz 1.9
		owo: oωo 0.3.8+1.18
		oxidized: Oxidized 1.5.0
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		paintings: Paintings++ 1.0.0.6
		patchouli: Patchouli 1.18-60-FABRIC
		pehkui: Pehkui 3.0.0+1.14.4-1.18
		petowner: Pet Owner 1.8.2-1.18-pre4+
		pigsteel: Pigsteel Mod 1.6.6
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		pling: Pling 1.5.0
		plushies: Plushie Mod 1.1
		polymer: Polymer 0.2.0-beta.8+1.18
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.8+1.18
		presencefootsteps: Presence Footsteps 1.4.0
		pugh_lib: Pugh Lib 1.2.12
		pugh_tools: Pugh Tools 1.1.14
		puzzleslib: Puzzles Lib 3.1.0
		quarrymod: Industial Quarry Mod 0.5.3
		quarryplus: QuarryPlus 18.0.458
		quartzelv: Quartz Elevator 2.0.0+1.18
		quickshulker: Quick Shulker 1.3.1-1.18
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0-beta.4
		redstonebits: Redstone Bits 1.6.0
		replanter: Replanter 1.3
		repurposed_structures: Repurposed Structures 3.1.10+1.18.1
		respawnablepets: Respawnable Pets 1.18-1
		rhino: Rhino 1800.1.6-build.81
		rightclickharvest: Right Click Harvest 1.5.1
		ring_of_enderchest: Ring of Enderchest 1.2.16
		ring_of_growth: Ring Of Growth 1.2.16
		ring_of_miner: Ring Of Miner 1.3.16
		ringsofascension: Rings of Ascension 1.0
		rocks: This Rocks! 1.5.2
		roughlyenoughitems: Roughly Enough Items 7.0.352
		satin: Satin 1.7.0
		seedfix: Seed Fix 1.0.0
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		sgui: sgui 1.0.0-rc6+1.18-pre5
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		shulkerutils: shulkerutils 1.0.4-1.18
		simple_backpack: SimpleBackpack 1.2.25
		simplegrinder: Simple Grinder 18.0.1
		simpleteleporters: Simple Teleporters 2.3.0
		skinlayers: 3d Skin Layers 1.3.1
		slotlock: SlotLock 1.0.4-BETA+1.18
		smootherbedrock: Smoother Bedrock 1.0.3
		sodium: Sodium 0.4.0-alpha5+build.9
		someforgepatchesported: Some Forge Patches Ported 1.0.1
		sound_physics_remastered: Sound Physics Remastered 1.18.1-1.0.3
		spark: spark 1.6.3
		spruceui: SpruceUI 3.3.0+1.17
		stacc: Stacc 1.2.3
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
		stoneholm: Stoneholm 1.4.1
		storagecabinet: Storage Cabinet 1.4.2
		strawdummy: Straw Dummy 1.6.0
		structurized: Structurized 1.4.0+1.18
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.1.0-beta.4
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0_b0.1.8
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		textile_backup: Textile Backup 2.3.0-1.18
		things: Things 0.2.8+1.18
		thonkutil: ThonkUtil 1.3
		timeinabottle: Time in a Bottle 1.6-mc1.17-fabric
		toms_storage: Tom's Simple Storage Mod 1.1.19
		tooltipfix: ToolTip Fix 1.0.4-1.18
		totemmod: Wither Totems Mod 0.3.4-1.18-rc2
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.0.0
		tradingpost: Trading Post 3.1.0
		trashslot: TrashSlot 11.0.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.1.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.2
		twm: The Wild Mod 0.2
		universal-graves: Universal Graves 1.2.2+1.18
		urns: Urns 1.0.1
		vanilla_degus: Vanilla Degus 1.3.0
		villager-hats: Villager Hats Mod 1.2.1
		villagernames: Villager Names 2.0.2
		visuality: Visuality 0.3.3
		voicechat: Simple Voice Chat 1.18.1-2.1.22
		voidtotem: VoidTotem (Fabric) 1.18.1-1.1.0
		voidz: VoidZ 1.0.5
		waterdripsound: Drip Sounds 1.18-0.3.0
		waystones: Waystones 2.3.4
		wmitaf: WMITAF 2.1.5
		wolveswitharmor: Wolves With Armor 1.7.0-1.18
		wthit: wthit 4.3.1
		xaerominimap: Xaero's Minimap 21.22.3.1
		xaeroworldmap: Xaero's World Map 1.18.6.1
		yosbr: YOSBR 0.1.1
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) UHD Graphics 630 GL version 4.1 INTEL-16.1.10, Intel Inc.
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, loadmyresources.hiddenpack
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader)

**Comment by Kasax007** [comment]
Hey, thanks for uplaoding. What version are you using?

**Comment by JetPorkins** [comment]
Whoops, sorry. I'm using Dreamcraft 1.18.1 v3 Released on 12/17

**Comment by Kasax007** [comment]
I just released the v4 version of the modpack. It should appear in the curse forge launcher very soon hopefully. I would like to ask you to try that. I have looked through your crash log but couldn't spot any issue at first glance. 
I hope v4 works for you since that fixed a lot of issues.

**Comment by JetPorkins** [comment]
ok cool, thanks, I'll keep an eye out for it!
